[package]
name = "tls"
version = "0.0.2"
description = "Bindings for libressl's libtls"
homepage = "https://github.com/manuels/libtls.rs"
license = " GPL-2.0"
authors = ["Manuel Schölling <manuel.schoelling@gmx.de>"]
